import './globals.css'
import localFont from 'next/font/local'

const myFont = localFont({
  src: "./assets/fonts/Pretandard/woff2/PretendardVariable.woff2"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
